# analysis_options.yaml

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    prefer_final_locals: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    unnecessary_this: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
