name: Delbites
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # [FIXED] Versi intl disesuaikan agar cocok dengan flutter_localizations
  intl: ^0.19.0
  
  # Sisa dependencies Anda
  flutter_rating_bar: ^4.0.0
  uuid: ^3.0.7
  webview_flutter: ^4.2.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  curved_navigation_bar: ^1.0.6
  http: ^1.0.3
  dio: ^5.8.0+1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  firebase_messaging: ^15.2.5
  device_info_plus: ^10.0.0
  path_provider: ^2.0.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  permission_handler: ^11.0.1
  logger: ^2.0.2
  flutter_inappwebview: ^6.0.0-beta.22


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo1.png

